name: Deploy Preview

on:
  pull_request:
    branches:
      - main # Ou substitua pela branch principal do seu repositório

  push:
    branches-ignore:
      - main # Apenas branches fora da principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        env:
          BASE_PATH: /preview/${{ github.event.pull_request.number || github.ref_name }}
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: preview/${{ github.event.pull_request.number || github.ref_name }}
